---
# Compile
- name: install uhubctl dependencies
  retries: 3
  delay: 10
  apt:
    state: present
    name: [
      'libusb-1.0-0-dev',
      'libusb-1.0-0',
    ]
- name: clone uhubctl
  retries: 3
  delay: 10
  git:
    repo: https://github.com/mvp/uhubctl.git
    dest: /usr/local/src/uhubctl
    clone: yes
    update: yes
    version: "{{ uhubctl_version }}"
  register: uhubctl_repo
- debug:
    var: uhubctl_repo
- name: set pi user as owner of uhubctl folder
  file:
    path: /usr/local/src/uhubctl
    owner: pi
    recurse: true
  notify:
    - make uhubctl
    - install uhubctl
- meta: flush_handlers