---
# Compile
- name: install uhubctl dependencies
  apt:
    state: present
    name: [
      'libusb-1.0-0-dev',
      'libusb-1.0-0',
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed
- name: clone uhubctl
  git:
    repo: https://github.com/mvp/uhubctl.git
    dest: /usr/local/src/uhubctl
    clone: yes
    update: yes
    version: "{{ uhubctl_version }}"
  register: uhubctl_repo
  retries: 3
  delay: 10
  until: not uhubctl_repo.failed
- name: set pi user as owner of uhubctl folder
  file:
    path: /usr/local/src/uhubctl
    owner: pi
    recurse: true
- name: make uhubctl
  become: false
  make:
  args:
    chdir: /usr/local/src/uhubctl
  when: uhubctl_repo.changed
- name: install uhubctl
  make:
    target: install
  args:
    chdir: /usr/local/src/uhubctl
  when: uhubctl_repo.changed