---
# Compile
- name: install uhubctl dependencies
  retries: 3
  delay: 10
  apt:
    state: present
    name: [
      'libusb-1.0-0-dev',
      'libusb-1.0-0',
    ]
- name: clone uhubctl
  retries: 3
  delay: 10
  git:
    repo: https://github.com/mvp/uhubctl.git
    dest: /usr/local/src/uhubctl
    clone: yes
    update: yes
    version: "{{ uhubctl_version }}"
  register: uhubctl_repo
  notify:
    - set pi user as owner
    - make uhubctl
    - install uhubctl
- debug:
    var: uhubctl_repo
