---
# install webmin for easy management
- name: install webmin dependencies
  apt:
    state: present
    name: [
      'perl',
      'python',
      'openssl',
      'libnet-ssleay-perl',
      'libauthen-pam-perl',
      'libpam-runtime',
      'libio-pty-perl',
      'apt-show-versions'
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed
- name: check webmin already installed
  apt:
    name: webmin
    state: present
  ignore_errors: yes
  no_log: true
  register: webmin
- name: install webmin
  apt:
    deb: http://prdownloads.sourceforge.net/webadmin/webmin_{{ webmin_version }}_all.deb
    state: present
  register: result
  retries: 3
  delay: 30
  until: not result.failed
  when: webmin.failed