---
# install webmin for easy management
- name: install webmin dependencies
  retries: 3
  delay: 10
  apt:
    state: present
    name: [
      'perl',
      'python',
      'openssl',
      'libnet-ssleay-perl',
      'libauthen-pam-perl',
      'libpam-runtime',
      'libio-pty-perl',
      'apt-show-versions'
    ]
- name: install webmin
  retries: 3
  delay: 30
  apt:
    deb: http://prdownloads.sourceforge.net/webadmin/webmin_{{ webmin_version }}_all.deb
    state: present