---
# tasks file for pi_stretch_common
- name: disable BLE
  blockinfile:
    path: /boot/config.txt
    state: present
    block: |
      # Disable BLE
      dtoverlay=pi3-disable-bt
- name: disable BLE services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items: [
    'hciuart.service',
    'bluetooth',
    'bluetooth.service',
  ]
- name: install disable-hdmi.service
  template:
    src: disable-hdmi.service.ini
    dest: /lib/systemd/system/disable-hdmi.service
    mode: 0755
  notify:
    - reload systemd
- name: disable HDMI
  systemd:
    name: disable-hdmi.service
    enabled: yes
    state: restarted
- name: reduce GPU RAM
  blockinfile:
    path: /boot/config.txt
    state: present
    block: |
      # Reduce GPU RAM to 16MB
      gpu_mem=16
- name: change pi user password
  user:
    name: pi
    password: "{{ pi_password }}"
  when: pi_password is defined
- name: change root password
  user:
    name: root
    password: "{{ pi_root_password }}"
  when: pi_root_password is defined