---
# tasks file for pi_stretch_common
- name: install raspberry pi common packages
  become: yes
  apt:
    state: present
    name: "{{ pi_common_packages }}"
  register: result
  retries: 3
  delay: 10
  until: not result.failed
- name: generate en_US locale
  become: yes
  locale_gen:
    name: en_US
    state: present
- name: configure locale
  become: yes
  command: update-locale LANG=en_US.utf8 LC_ALL=en_US.utf8 LANGUAGE=en_US:en
- name: configure watchdog
  become: yes
  blockinfile:
    path: /etc/watchdog.conf
    block: |
      admin           = {{ watchdog_admin }}
      interval        = {{ watchdog_interval }}
      retry-timeout   = {{ watchdog_retry_timeout }}
      repair-maximum  = {{ watchdog_repair_maximum }}
      log-dir         = {{ watchdog_log }}
      max-load-1      = {{ watchdog_max_load_1 }}
      max-load-5      = {{ watchdog_max_load_5 }}
      max-load-15     = {{ watchdog_max_load_15 }}
      watchdog-device = {{ watchdog_device }}
      watchdog-timeout = {{ watchdog_timeout }}
      sigterm-delay   = {{ watchdog_sigterm_delay }}
      {% if watchdog_interface is defined %}
      interface       = {{ watchdog_interface }}
      {% endif %}
      {% if watchdog_pings is defined %}
      {% for ping in watchdog_pings %}
      ping            = {{ ping }}
      ping-count      = 1
      {% endfor %}
      {% endif %}
  notify:
    - restart watchdog
    - reboot
- name: modify boot config
  become: yes
  blockinfile:
    path: /boot/config.txt
    state: present
    block: |
      gpu_mem={{ pi_gpu_mem }}
      {% if pi_force_turbo is defined %}
      force_turbo={{ pi_force_turbo }}
      {% endif %}
      {% if pi_arm_freq is defined %}
      arm_freq={{ pi_arm_freq }}
      {% endif %}
      {% if not pi_ble %}
      # Disable BLE
      dtoverlay=pi3-disable-bt
      {% endif %}
      {% if pi_spi is defined and pi_spi %}
      dtparam=spi=on
      {% endif %}
      {% if pi_over_voltage is defined %}
      # Manually set voltage
      over_voltage={{ pi_over_voltage }}
      {% endif %}
  notify:
    - reboot
- name: disable BLE & HCIUART services
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - hciuart
    - bluetooth
- name: disable default raspberry pi swap
  become: yes
  command: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  when: swap is defined and swap
- name: install disable-hdmi.service
  become: yes
  template:
    src: disable-hdmi.service.ini
    dest: /lib/systemd/system/disable-hdmi.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - disable HDMI
    - reboot
- name: install iftop configuration file
  become: yes
  template:
    src: iftoprc.ini
    dest: "{{ item.dest }}/.iftoprc"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0600
  loop:
    - { dest: "/home/{{ ansible_user}}", owner: "{{ ansible_user }}", group: "{{ ansible_user }}" }
    - { dest: /root, owner: root, group: root }
- name: configure and secure sshd
  become: yes
  blockinfile:
    path: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -T -c %s
    block: |
      PermitRootLogin {{ 'yes' if sshd_permit_root_login else 'no' }}
      PasswordAuthentication {{ 'yes' if sshd_password_authentication else 'no' }}
      ClientAliveInterval 10
  notify:
    - restart ssh
- name: change pi user password
  become: yes
  user:
    name: pi
    password: "{{ pi_password }}"
  no_log: yes
  when: pi_password is defined
- name: change root password
  become: yes
  user:
    name: root
    password: "{{ pi_root_password }}"
  no_log: yes
  when: pi_root_password is defined
- meta: flush_handlers