---
# tasks file for pi-common
- name: update apt
  apt:
    update_cache: yes
- name: upgrade apt packages
  apt:
    upgrade: yes
- name: install common raspbian packages
  apt:
    state: present
    name: [
      'git',
      'psmisc',
      'uptimed',
      'build-essential',
      'screen',
      'libtool',
      'automake',
      'pkg-config',
      'raspberrypi-kernel-headers',
      'dh-autoreconf'
    ]
- name: set host name to hostname variable
  lineinfile:
    dest: /etc/hostname
    regexp: '^raspberrypi'
    line: "{{ pi_hostname }}"
  when: pi_hostname is defined
- name: set hostname to ansible host
  lineinfile:
    dest: /etc/hostname
    regexp: '^raspberrypi'
    line: "{{ ansible_host }}"
  when: hostname is undefined
- include: install-webmin.yml
- include: compile-uhubctl.yml
- name: reboot
  reboot:
