---
# tasks file for pi_stretch_common
- name: upgrade apt packages
  apt:
    cache_valid_time: 84600
    upgrade: yes
  register: result
  retries: 3
  delay: 10
  until: not result.failed
- name: upgrade apt dist
  apt:
    upgrade: dist
  register: result
  retries: 3
  delay: 10
  until: not result.failed
- name: install common raspbian packages
  apt:
    state: present
    name: [
      'git',
      'psmisc',
      'uptimed',
      'build-essential',
      'screen',
      'libtool',
      'automake',
      'pkg-config',
      'raspberrypi-kernel-headers',
      'dh-autoreconf'
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed
- include: install-webmin.yml
- include: compile-uhubctl.yml
- name: set host name
  lineinfile:
    dest: /etc/hostname
    backrefs: yes
    regexp: '^raspberrypi$'
    line: "{% if pi_hostname is defined %}{{ pi_hostname }}{% else %}{{ ansible_host }}{% endif %}.{{ domain }}"
- name: disable BLE
  blockinfile:
    path: /boot/config.txt
    state: present
    block: |
      # Disable BLE
      dtoverlay=pi3-disable-bt
- name: disable BLE services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items: [
    'hciuart.service',
    'bluetooth',
    'bluetooth.service',
  ]
- name: install disable-hdmi.service
  template:
    src: disable-hdmi.service.ini
    dest: /lib/systemd/system/disable-hdmi.service
    mode: 0755
- name: reload systemd
  systemd:
    daemon_reload: yes
- name: disable HDMI
  systemd:
    name: disable-hdmi.service
    enabled: yes
    state: restarted
- name: reduce GPU RAM
  blockinfile:
    path: /boot/config.txt
    state: present
    block: |
      # Reduce GPU RAM to 16MB
      gpu_mem=16
- name: change pi user password
  user:
    name: pi
    password: "{{ pi_password }}"
  when: pi_password is defined
- name: change root password
  user:
    name: root
    password: "{{ pi_root_password }}"
  when: pi_root_password is defined
- name: reboot to update changes
  reboot: