---
# tasks file for pi_stretch_common
- name: update apt
  retries: 3
  delay: 10
  apt:
    update_cache: yes
- name: upgrade apt packages
  retries: 3
  delay: 10
  apt:
    upgrade: yes
- name: install common raspbian packages
  retries: 3
  delay: 10
  apt:
    state: present
    name: [
      'git',
      'psmisc',
      'uptimed',
      'build-essential',
      'screen',
      'libtool',
      'automake',
      'pkg-config',
      'raspberrypi-kernel-headers',
      'dh-autoreconf'
    ]
- include: install-webmin.yml
- include: compile-uhubctl.yml
- name: set host name to hostname variable
  lineinfile:
    dest: /etc/hostname
    regexp: '^raspberrypi'
    line: "{{ pi_hostname }}"
  when: pi_hostname is defined
- name: set hostname to ansible host
  lineinfile:
    dest: /etc/hostname
    regexp: '^raspberrypi'
    line: "{{ ansible_host }}"
  when: pi_hostname is undefined
- name: disable BLE
  blockinfile:
    path: /boot/config.txt
    state: present
    block: |
      # Disable BLE
      dtoverlay=pi3-disable-bt
- name: disable BLE services
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items: [
    'hciuart.service',
    'bluealsa.service',
    'bluetooth.service'
  ]


