---
# handlers file for pi-stretch-common
- name: set pi user as owner
  file:
    path: /usr/local/src/uhubctl
    owner: pi
    recurse: true
  when: uhubctl_repo.changed
- name: make uhubctl
  become: false
  make:
  args:
    chdir: /usr/local/src/uhubctl
  when: uhubctl_repo.changed
- name: install uhubctl
  make:
    target: install
  args:
    chdir: /usr/local/src/uhubctl
  when: uhubctl_repo.changed