---
# handlers file for pi_stretch_common
- name: reload systemd
  systemd:
    daemon_reload: yes
- name: disable HDMI
  systemd:
    name: disable-hdmi
    enabled: yes
    state: restarted
- name: reboot
  reboot:
  notify:
    - setup again
- name: setup again
  setup: