---
# handlers file for pi_stretch_common
- name: reload systemd
  systemd:
    daemon_reload: yes
- name: disable HDMI
  systemd:
    name: disable-hdmi
    enabled: yes
    state: restarted
- name: reboot
  reboot:
  notify:
    - setup again
- name: setup again
  setup:
- name: restart watchdog
  systemd:
    name: watchdog.service
    state: started
    enabled: yes
- name: restart ssh
  service:
    name: ssh
    state: restarted